import os
import time
import smtplib
from email.message import EmailMessage

import streamlit as st
from dotenv import load_dotenv
from ultralytics import YOLO
from streamlit_webrtc import VideoProcessorBase, webrtc_streamer


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_PATH = "models/best.pt"

# Minimum time between two fire alert emails
ALERT_COOLDOWN = 60


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Fire Detection System",
    page_icon="🔥",
    layout="wide",
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    .main-title {
        text-align: center;
        font-size: 2.4rem;
        font-weight: 700;
        margin-bottom: 0.2rem;
    }

    .subtitle {
        text-align: center;
        color: #777;
        margin-bottom: 1.5rem;
    }

    .status-box {
        padding: 20px;
        border-radius: 12px;
        text-align: center;
        margin-bottom: 15px;
    }

    .fire-status {
        background-color: #ffdddd;
        border: 2px solid #ff4444;
    }

    .smoke-status {
        background-color: #fff1cc;
        border: 2px solid #ff9900;
    }

    .safe-status {
        background-color: #ddf5df;
        border: 2px solid #32a852;
    }

    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">🔥 Real-Time Fire Detection System</div>',
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="subtitle">'
    "YOLO26-based Fire, Smoke and Other Object Detection"
    "</div>",
    unsafe_allow_html=True,
)


# ============================================================
# LOAD YOLO MODEL
# ============================================================

@st.cache_resource
def load_model():
    return YOLO(MODEL_PATH)


model = load_model()


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("⚙️ Detection Settings")

confidence_threshold = st.sidebar.slider(
    "Confidence Threshold",
    min_value=0.05,
    max_value=1.00,
    value=0.25,
    step=0.05,
)

st.sidebar.markdown("---")

st.sidebar.subheader("Model Information")

st.sidebar.write("**Model:** YOLO26n")
st.sidebar.write("**Classes:** Fire / Other / Smoke")
st.sidebar.write("**Input:** Webcam")
st.sidebar.write("**Weights:** best.pt")

st.sidebar.markdown("---")

st.sidebar.subheader("📧 Email Alerts")

if EMAIL_SENDER and EMAIL_RECEIVER:

    st.sidebar.success("Email alerts configured")

    st.sidebar.write(
        f"Recipient: `{EMAIL_RECEIVER}`"
    )

    st.sidebar.write(
        f"Cooldown: `{ALERT_COOLDOWN} seconds`"
    )

else:

    st.sidebar.warning(
        "Email credentials are not configured."
    )


st.sidebar.markdown("---")

st.sidebar.info(
    "This system is a computer-vision prototype "
    "and should not be used as a certified fire-safety alarm."
)


# ============================================================
# EMAIL FUNCTION
# ============================================================

def send_fire_alert(confidence):
    """
    Send an email when fire is detected.
    """

    if not EMAIL_SENDER:
        print("EMAIL_SENDER is not configured.")
        return False

    if not EMAIL_PASSWORD:
        print("EMAIL_PASSWORD is not configured.")
        return False

    if not EMAIL_RECEIVER:
        print("EMAIL_RECEIVER is not configured.")
        return False

    try:

        message = EmailMessage()

        message["Subject"] = (
            "🔥 FIRE DETECTED - Fire Detection System"
        )

        message["From"] = EMAIL_SENDER
        message["To"] = EMAIL_RECEIVER

        message.set_content(
            f"""
Fire Detection Alert

The YOLO26 fire detection system has detected FIRE.

Detection Details
-----------------
Class: FIRE
Confidence: {confidence * 100:.2f}%

Please check the camera immediately.

This is an automated alert generated by the
Fire Detection System.
"""
        )

        with smtplib.SMTP_SSL(
            "smtp.gmail.com",
            465
        ) as server:

            server.login(
                EMAIL_SENDER,
                EMAIL_PASSWORD
            )

            server.send_message(message)

        print(
            f"Fire alert email sent successfully "
            f"to {EMAIL_RECEIVER}"
        )

        return True

    except Exception as error:

        print(
            f"Failed to send fire alert email: {error}"
        )

        return False


# ============================================================
# VIDEO PROCESSOR
# ============================================================

class VideoProcessor(VideoProcessorBase):

    def __init__(self):

        self.model = model

        # Detection settings
        self.confidence = confidence_threshold

        # FPS
        self.last_time = time.time()
        self.fps = 0.0

        # Detection counts
        self.fire_count = 0
        self.smoke_count = 0
        self.other_count = 0

        # Highest confidence detection
        self.max_confidence = 0.0
        self.detected_class = None

        # Email alert state
        self.last_alert_time = 0
        self.fire_alert_sent = False

        # Email status
        self.email_status = "No alert sent"


    # ========================================================
    # PROCESS EACH VIDEO FRAME
    # ========================================================

    def recv(self, frame):

        # ----------------------------------------------------
        # Convert WebRTC frame to OpenCV
        # ----------------------------------------------------

        img = frame.to_ndarray(
            format="bgr24"
        )

        # ----------------------------------------------------
        # YOLO inference
        # ----------------------------------------------------

        results = self.model.predict(
            source=img,
            conf=self.confidence,
            verbose=False,
        )

        result = results[0]

        # ----------------------------------------------------
        # Reset detection values
        # ----------------------------------------------------

        self.fire_count = 0
        self.smoke_count = 0
        self.other_count = 0

        self.max_confidence = 0.0
        self.detected_class = None

        # ----------------------------------------------------
        # Process detections
        # ----------------------------------------------------

        if result.boxes is not None:

            for box in result.boxes:

                class_id = int(
                    box.cls[0]
                )

                confidence = float(
                    box.conf[0]
                )

                class_name = (
                    self.model.names[class_id]
                    .lower()
                )

                # --------------------------------------------
                # Find highest confidence detection
                # --------------------------------------------

                if confidence > self.max_confidence:

                    self.max_confidence = confidence

                    self.detected_class = (
                        class_name
                    )

                # --------------------------------------------
                # Count classes
                # --------------------------------------------

                if class_name == "fire":

                    self.fire_count += 1

                elif class_name == "smoke":

                    self.smoke_count += 1

                elif class_name == "other":

                    self.other_count += 1

        # ====================================================
        # EMAIL ALERT LOGIC
        # ====================================================

        current_time = time.time()

        # Fire detected
        if self.fire_count > 0:

            # Check whether enough time has passed
            cooldown_finished = (
                current_time - self.last_alert_time
                >= ALERT_COOLDOWN
            )

            # Send only if an alert has not already
            # been sent for the current fire event
            if (
                not self.fire_alert_sent
                and cooldown_finished
            ):

                email_sent = send_fire_alert(
                    self.max_confidence
                )

                if email_sent:

                    self.fire_alert_sent = True

                    self.last_alert_time = (
                        current_time
                    )

                    self.email_status = (
                        "📧 Fire alert email sent"
                    )

                else:

                    self.email_status = (
                        "⚠️ Email failed"
                    )

        # ----------------------------------------------------
        # No fire detected
        # ----------------------------------------------------

        else:

            # Reset the event state.
            #
            # The next new fire detection can
            # generate another email.

            self.fire_alert_sent = False

        # ====================================================
        # DRAW YOLO RESULTS
        # ====================================================

        annotated_frame = result.plot()

        # ====================================================
        # FPS CALCULATION
        # ====================================================

        current_frame_time = time.time()

        elapsed = (
            current_frame_time
            - self.last_time
        )

        if elapsed > 0:

            self.fps = 1.0 / elapsed

        self.last_time = (
            current_frame_time
        )

        # ====================================================
        # ADD FPS TO VIDEO
        # ====================================================

        import cv2

        cv2.putText(
            annotated_frame,
            f"FPS: {self.fps:.1f}",
            (20, 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255, 255, 255),
            2,
        )

        # ====================================================
        # RETURN FRAME
        # ====================================================

        return frame.from_ndarray(
            annotated_frame,
            format="bgr24",
        )


# ============================================================
# MAIN DASHBOARD
# ============================================================

st.markdown("### 📹 Live Camera")


camera_col, status_col = st.columns(
    [2.2, 1]
)


# ============================================================
# CAMERA
# ============================================================

with camera_col:

    webrtc_ctx = webrtc_streamer(
        key="fire-detection",

        video_processor_factory=VideoProcessor,

        media_stream_constraints={
            "video": True,
            "audio": False,
        },

        async_processing=True,
    )


# ============================================================
# STATUS PANEL
# ============================================================

with status_col:

    st.markdown(
        "### 🚨 Detection Status"
    )

    status_placeholder = st.empty()

    st.markdown(
        "### 📊 Detection Summary"
    )

    fire_metric = st.empty()

    smoke_metric = st.empty()

    other_metric = st.empty()

    st.markdown(
        "### 🎯 Highest Confidence"
    )

    confidence_placeholder = st.empty()

    st.markdown(
        "### ⚡ Performance"
    )

    fps_placeholder = st.empty()

    st.markdown(
        "### 📧 Email Alert"
    )

    email_placeholder = st.empty()


# ============================================================
# UPDATE DASHBOARD METRICS
# ============================================================

if webrtc_ctx.video_processor:

    processor = webrtc_ctx.video_processor

    while webrtc_ctx.state.playing:

        # ====================================================
        # DETECTION STATUS
        # ====================================================

        if processor.fire_count > 0:

            status_placeholder.markdown(
                f"""
                <div class="status-box fire-status">

                    <h2>🔥 FIRE DETECTED</h2>

                    <p>
                    Fire objects:
                    <strong>
                    {processor.fire_count}
                    </strong>
                    </p>

                </div>
                """,
                unsafe_allow_html=True,
            )

        elif processor.smoke_count > 0:

            status_placeholder.markdown(
                f"""
                <div class="status-box smoke-status">

                    <h2>💨 SMOKE DETECTED</h2>

                    <p>
                    Smoke objects:
                    <strong>
                    {processor.smoke_count}
                    </strong>
                    </p>

                </div>
                """,
                unsafe_allow_html=True,
            )

        else:

            status_placeholder.markdown(
                """
                <div class="status-box safe-status">

                    <h2>✓ NO FIRE DETECTED</h2>

                    <p>
                    No fire or smoke detected
                    </p>

                </div>
                """,
                unsafe_allow_html=True,
            )

        # ====================================================
        # DETECTION COUNTS
        # ====================================================

        fire_metric.metric(
            "🔥 Fire",
            processor.fire_count,
        )

        smoke_metric.metric(
            "💨 Smoke",
            processor.smoke_count,
        )

        other_metric.metric(
            "📦 Other",
            processor.other_count,
        )

        # ====================================================
        # HIGHEST CONFIDENCE
        # ====================================================

        if processor.detected_class:

            confidence_placeholder.metric(
                processor.detected_class.upper(),
                f"{processor.max_confidence * 100:.1f}%",
            )

        else:

            confidence_placeholder.metric(
                "Detection",
                "None",
            )

        # ====================================================
        # FPS
        # ====================================================

        fps_placeholder.metric(
            "FPS",
            f"{processor.fps:.1f}",
        )

        # ====================================================
        # EMAIL STATUS
        # ====================================================

        email_placeholder.write(
            processor.email_status
        )

        # ====================================================
        # UPDATE RATE
        # ====================================================

        time.sleep(0.1)