import os
import smtplib

from datetime import datetime
from email.message import EmailMessage

from src.config import (
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECEIVER,
)


def send_fire_alert(
    confidence,
    snapshot_path=None,
):
    """
    Send a fire detection email with an optional
    detection snapshot attachment.
    """

    if not EMAIL_SENDER:
        print("EMAIL_SENDER is not configured.")
        return False

    if not EMAIL_PASSWORD:
        print("EMAIL_PASSWORD is not configured.")
        return False

    if not EMAIL_RECEIVER:
        print("EMAIL_RECEIVER is not configured.")
        return False

    try:

        # Current timestamp
        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        # Create email
        message = EmailMessage()

        message["Subject"] = (
            "🔥 FIRE DETECTED - Fire Detection System"
        )

        message["From"] = EMAIL_SENDER
        message["To"] = EMAIL_RECEIVER

        message.set_content(
            f"""
Fire Detection Alert
====================

The YOLO26 fire detection system has detected FIRE.

Detection Details
-----------------
Class       : FIRE
Confidence  : {confidence * 100:.2f}%
Time        : {timestamp}

A snapshot of the detection is attached to this email.

Please check the camera immediately.

This is an automated alert generated by the
Fire Detection System.
"""
        )

        # ====================================================
        # ATTACH SNAPSHOT
        # ====================================================

        if (
            snapshot_path
            and os.path.exists(snapshot_path)
        ):

            with open(
                snapshot_path,
                "rb",
            ) as image_file:

                image_data = image_file.read()

            message.add_attachment(
                image_data,
                maintype="image",
                subtype="jpeg",
                filename=os.path.basename(
                    snapshot_path
                ),
            )

        # ====================================================
        # SEND EMAIL
        # ====================================================

        with smtplib.SMTP_SSL(
            "smtp.gmail.com",
            465,
        ) as server:

            server.login(
                EMAIL_SENDER,
                EMAIL_PASSWORD,
            )

            server.send_message(message)

        print(
            f"Fire alert email sent successfully "
            f"to {EMAIL_RECEIVER}"
        )

        return True

    except Exception as error:

        print(
            f"Failed to send fire alert email: {error}"
        )

        return False