import smtplib
from email.message import EmailMessage

from src.config import (
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECEIVER,
)


def send_fire_alert(confidence):
    """
    Send an email alert when fire is detected.
    """

    if not EMAIL_SENDER:
        print("EMAIL_SENDER is not configured.")
        return False

    if not EMAIL_PASSWORD:
        print("EMAIL_PASSWORD is not configured.")
        return False

    if not EMAIL_RECEIVER:
        print("EMAIL_RECEIVER is not configured.")
        return False

    try:

        message = EmailMessage()

        message["Subject"] = (
            "🔥 FIRE DETECTED - Fire Detection System"
        )

        message["From"] = EMAIL_SENDER
        message["To"] = EMAIL_RECEIVER

        message.set_content(
            f"""
Fire Detection Alert

The YOLO26 fire detection system has detected FIRE.

Detection Details
-----------------
Class: FIRE
Confidence: {confidence * 100:.2f}%

Please check the camera immediately.

This is an automated alert generated by the
Fire Detection System.
"""
        )

        with smtplib.SMTP_SSL(
            "smtp.gmail.com",
            465,
        ) as server:

            server.login(
                EMAIL_SENDER,
                EMAIL_PASSWORD,
            )

            server.send_message(message)

        print(
            f"Fire alert email sent successfully "
            f"to {EMAIL_RECEIVER}"
        )

        return True

    except Exception as error:

        print(
            f"Failed to send fire alert email: {error}"
        )

        return False